### ISSUE TITLE
Finalize annotations for the signature manifest

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/specifications#103]
We currently have the following to enable filtering on the different signatures:
```json
"annotations": {
  "org.cncf.notary.signature.subject": "wabbit-networks.io"
}
```

This will need more details for how the key is identified for filtering.

**Comment by iamsamirzon** [comment]
Closing, as we have defined the annotations for signature manifest here https://github.com/notaryproject/notaryproject/blob/main/signature-specification.md#storage.

Plus the filtering aspect called out here is a duplicate of https://github.com/notaryproject/notation/issues/63
