### ISSUE TITLE
Release Candidate Signature Format

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/specifications#105]
**Summary**
The final release candidate signature format. This may or may not be the same as the one in Alpha release.

Also as part of this issue we should also followup on open comments from PR #93 
- [x] [We may want to allow the certificate chain to be transmitted via a secondary method (e.g. a separate blob from the envelope)](https://github.com/notaryproject/notaryproject/pull/93#discussion_r682854117 )
- [x] [Is this pointing to internet accessible revocation servers, and if so, how would a disconnected environment without access to the internet process this? Will clients be able to create a mapping from a public server to a private server that mirrors this information?](https://github.com/notaryproject/notaryproject/pull/93#discussion_r682855823)

**Intended Outcome**
The specification PR is merged
**Additional context**
Need to start now on this, to define spec; and then decide the incremental approach, and when to release it;

**Comment by iamsamirzon** [comment]
Discussed live in a meeting on 7/8/2022 that JWS was the format we agreed on for the initial release, as discussed in the NV2 meeting on 4/28/2022 - https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw?both#April-28-2022

**Comment by dtzar** [comment]
Discussed on the call the idea of for RC-2 to include a default signing format but have an option to switch to COSE or JWS.  This is covered in other issues, so still good to close this item out.
