### ISSUE TITLE
Feature Branches for Automated Builds

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/specifications#120]
As end-users start implementing notary, we'd like to avoid them having to build from source to receive pre-release updates.
We could provide them binaries from personal forks, but that's not a very secure solution, particularly for a security project.

This involves two specific items:

1. Having automated builds, based on merges into specific branches. A user could download a specific build, validate, provide feedback. If we make a quick fix to address their feedback, the PR is made, reviewed and merged. Once the PR is merged, any tests are run, and a release is made, The user can pickup the binary and continue their validations. 
2. Where should incubation work be merged? We previously said main would represent the active development. If a feature is in development, but not yet aligned with a spec, should it be in main? If we merge to main, we likely have more stringent PR reviews, slowing down incubation. If we merge to main without stringent PR reviews, we have more code to cleanup later.

## Proposal

Build feature branches, with automated builds on merge.

As an example, we'll create a feature branch named `feat-kv-extensibility`, which is derived from main. Developers working on that feature will develop on their personal forks. As they wish to merge up code for usage and validation testing, the PR to `feat-kv-extensibility`. The PR review on that branch is less critical than what we'd apply to main. The code may lead, or be out of sync with a given spec as the feature team is validating ___.  As code is merged, a preview release is built using the following pattern {branch}+[YYMMDD]-[commit-hash]: `feat-kv-extensibility-20211216-efea`

**Comment by gokarnm** [comment]
LGTM

**Comment by NiazFK** [comment]
LGTM

**Comment by sudo-bmitch** [comment]
Should this be an issue for notation?

For pushing compiled code, if you don't want to create releases for every change, the two places I know to ship binaries are in a package (i.e. container image) or as a zip of the artifacts during the build. The former means you'll want an alias or something to avoid typing long docker run commands for every notation CLI. And the latter means downloading everything for every platform to get just the binaries you want, from a place that's not easily found, and which expires after 30 days. I'd be happy to hear if there are better options, but if not, just realize the limitations with what we have.

**Comment by SteveLasker** [comment]
> Should this be an issue for notation?

I was going to put it in notation, but it really applies to any notary sub-project, so I figured I'd capture it here, and we can update governance, based on the decision.

For the options, I was shooting for a solution where users can simply use a pre-release/feature binary. Container images work in some cases, but not all, or they can complicate the experience. 

There is a potential cleanup that we really don't want 100 builds, and we might do a cleanup of the feature branch builds once merged, but is there a concern with building a binary on merge? I'd actually suggest we do this off main as well as feature branches.

**Comment by sudo-bmitch** [comment]
I don't have any concerns with building the binary on merges, PRs, or feature branches, lots of GHA workflows do that. It's the distribution of those binaries that gets complicated. So if you plan to do that, I'd spell out that step in more detail.

**Comment by SteveLasker** [comment]
>It's the distribution of those binaries that gets complicated.  

Can you clarify the concerns?

The plan would simply be to make them available under releases, such as [notation releases](https://github.com/notaryproject/notation/releases),

**Comment by sudo-bmitch** [comment]
> The plan would simply be to make them available under releases, such as [notation releases](https://github.com/notaryproject/notation/releases),

Oh, I'm not sure I've ever seen anyone do that before for individual commits to feature branches. Most of us only cut a release on a tag. Gonna be spammy for anyone that likes to follow major updates to the project.

If you're open to suggestions, I'd recommend `actions/upload-artifact@v2`: https://github.com/actions/upload-artifact
It means users have to drill down in GHA, download a zip, and extract the binary from that zip, but it keeps the releases page a lot less cluttered until you're ready to tag something for a larger audience.

**Comment by sajayantony** [comment]
+1 to @sudo-bmitch on not cluttering the release page. This also affects GitHub notifications and would cause a release notification upon merge - https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#about-custom-notifications.

**Comment by yizha1** [comment]
Closed by https://github.com/notaryproject/notation/pull/149.
