### ISSUE TITLE
Proposal: Remove Artifact Expiry

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/specifications#141]
From [Trust Store and Trust Policy Specification:Artifact Expiry](https://github.com/notaryproject/notaryproject/blob/main/trust-store-trust-policy-specification.md#artifact-expiry)

I'd like to propose we remove this section. 
Why:
I'd suggest an artifact doesn't actually expire, or at least this is data that I don't believe we should build into the signature format.

What does expiring an artifact mean? Is this to infer an end of support/life of an artifact? Does that mean validation should fail?

If we take the concept of signing the purchase of a home, the signer bought the house, and the sale doesn't expire. It might get re-sold, but there's additional information added for whom is the new owner.

If I lease a property, the signature is valid after the lease expires. The contract for the lease ends, but should that be in the signature? Or, should there be additional claims made for the artifact? 

If software is being used after its end of support life, should it fail to validate? Having a separate claim that says artifact __ is end of life on _/_/_. But, what if that date gets extended? Or, just because its out of support, should a user not be able to run the software? I'm suggesting this information is important for evaluation, but shouldn't be embedded in a signature, rather we're developing better tools to support these scenarios.

As we get further into a claims based model, I'm sure we'll have many claims to be evaluated, through a policy engine. But, the signature validation should be more focused on the validity of the identity as associated to a claim and an artifact. Decoupling these will give us the granularity we need, as opposed to packing everything into the signature.

**Comment by iamsamirzon** [comment]
My personal suggestion will be to leave the specification as is and make it an implementation decision.  I think of signature or artifact expiry as a "best if used by" date that a publisher puts on the artifact. It is up to the consumer to decide if they want to do a "hard-fail-open" or "Warn-open" on signature expiry.   

In the property example, I agree the sale is not expiring. Same way the container image is not expiring. At re-sale time the new owner does a title check. Same way at signature expiry, a consumer should go and find out if there is  newer version of the artifact to use, or getting an updated signature from the publisher.

**Comment by SteveLasker** [comment]
The re-sale scenario is a perfect case. When you buy the property, do you know when you'll sell it? Even if you _plan_ to sell in 2 years, will you sell in 2 years, or 2 years and 3 months, or maybe you decide to sell in 5 years.

My point is expiry is not a good practice to create at the time of creation, because it's not a realistic value. It's an estimated value because it was all we had at the time some of these techs were created. 
As Notary is a fresh start, can we leave behind stale concepts, and not have so many dials that users get confused?

**Comment by SteveLasker** [comment]
Reviewing the [spec](https://github.com/notaryproject/notaryproject/blob/main/trust-store-trust-policy-specification.md)

> - **`signatureExpiry`**(*string*): This REQUIRED property specifies what implementation must do if the signature is expired.
      Supported values are `enforce` and `warn`.

We don't have an ignore. Since this property is REQUIRED, it can generate a LOT of noise in the system, hiding more actionable warnings.

My preference is to remove and defer to a more scalable solution for adding information as it becomes available after the initial artifact is released.

Alternatively, I'm suggesting the `signatureExpiry` property should be OPTIONAL, with a default of `skip`
