### ISSUE TITLE
Update Plug-in spec to support multiple signature formats

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/specifications#146]
To support multiple signature formats (https://github.com/notaryproject/notaryproject/pull/145) the [plug-in spec](https://github.com/notaryproject/notaryproject/blob/main/specs/plugin-extensibility.md) will need updates to support multiple signature/envelope formats. Specifically, JWT and COSE.

A desired outcome is the plug-in spec would specify a named parameter for what signature format is requested, and the plug-in APIs wouldn't need changing.

**Comment by gokarnm** [comment]
The spec already supports multiple envelope format using `signatureEnvelopeType`, in the [Signature Envelope Generator](https://github.com/notaryproject/notaryproject/blob/main/specs/plugin-extensibility.md#signature-envelope-generator) interface. Let me know if any other changes are required.

```
{
  "contract-version" : <major-version.minor-version>,
  
  // Complete key definition from /notation/config.JSON /signingKeys/keys with matching key name
  "keyDefinition" : <key definition>, 

  "payload" : <Base64 encoded payload to be signed>,
  
  // The type of payload - currently a descriptor
  "payloadType" : "application/vnd.oci.descriptor.v1+json",
  
  // The expected response signature envelope
  "signatureEnvelopeType" : "application/vnd.cncf.notary.v2.jws.v1"
}
```

**Comment by SteveLasker** [comment]
@shizhMSFT, can you confirm your question is answered and adding code doesn't change the plug-in spec?
