### ISSUE TITLE
Clarify Certificate Requirements

### ISSUE THREAD

**Issue by gokarnm** [notaryproject/specifications#157]
Clarify [certificate requirements](https://github.com/notaryproject/notaryproject/blob/main/signature-specification.md#certificate-requirements) section in signature specification. 

* Separate out requirements for signing certs and timestamping certs into different sections.
* Consider if want to specify requirements of other certificates in the chain
* Possibly address EKU restriction for signing cert #130 

cc: @priteshbandi

**Comment by gokarnm** [comment]
`verifyCertExtKeyUsage` in [spec.go](https://github.com/notaryproject/notation-go/blob/main/signature/jws/spec.go) should be updated once cert requirements are clarified.

**Comment by iamsamirzon** [comment]
#167  and #166  PR needs approval before this issue can be closed

**Comment by iamsamirzon** [comment]
@gokarnm  -Could you close this issue as this PR is now merged (https://github.com/notaryproject/notaryproject/pull/162).  

For the outstanding request of relaxing the EKU, there is a separate issue anyways. https://github.com/notaryproject/notaryproject/issues/130
