### ISSUE TITLE
Add new members and groups 

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/specifications#160]
Need a few groups and memberships aligned to ensure frictionless progress.

1. Add new member to the existing project-admin group  https://github.com/orgs/notaryproject/teams/notary-project-admins/members
    - David Tesar (https://github.com/dtzar) 
2.  Add new members to the  existing group for "Notation-maintainers" https://github.com/orgs/notaryproject/teams/notation-maintainers 
  -  This is the group which can add and merge code PRs in the "notation", "notation-go", "notation-go-core" libraries
  - Milind Gokarnm - https://github.com/gokarnm
  - Shiwei  - https://github.com/shizhMSFT
3. Create a new group for code-reviewers
   - This is the group which is a super set of the above group and does code reviews
   -  Milind Gokarnm - https://github.com/gokarnm
   - Shiwei  - https://github.com/shizhMSFT
   - Rakesh - https://github.com/rgnote 
   - Pritesh - https://github.com/priteshbandi
   - Quim - https://github.com/qmuntal 
   - Jonathan - https://github.com/jondonas

**Comment by iamsamirzon** [comment]
@SteveLasker , @NiazFK  - We will like your approval and action on this issue to expand the list of  members and groups as requested in the issue.

**Comment by SteveLasker** [comment]
LGTM

**Comment by dtzar** [comment]
I believe this is complete now so we can close, right? @SteveLasker @iamsamirzon

**Comment by iamsamirzon** [comment]
@dtzar  - Could you cross check if the "Code-reviewers" group #3 above was created? Items #1 and #2 were fixed.

**Comment by NiazFK** [comment]
LGTM

**Comment by dtzar** [comment]
I added the notation-code-reviewers group: https://github.com/orgs/notaryproject/teams/notation-code-reviewers

However, I cannot add anyone who is not a member of the notaryproject org nor do I have the permissions to invite people to the notaryproject org.  I'm guessing @SteveLasker you'll have to invite the code reviewers listed as members to the org then I can add them there.

<img width="525" alt="image" src="https://user-images.githubusercontent.com/3578906/176736382-0038b8c4-85bf-4e87-ae6f-118bb1f935bc.png">

**Comment by SteveLasker** [comment]
Everyone is now invited

**Comment by dtzar** [comment]
@rgnote @priteshbandi just need to accept the invite. 

Per the last community call @gokarnm said he had a draft for the code-reviewers group WIP he would PR, but IMO I don't think we should hold up on that to close this issue.

@iamsamirzon - we good to close this out now?

**Comment by SteveLasker** [comment]
I'm ok to close this, as the title is adding new members, and that's done.
We can add another issue for the governance updates, but I don't see that as critical at this point.

**Comment by gokarnm** [comment]
Can we add contributors from Shiwei's team too, @shizhMSFT could you provide a list?

**Comment by gokarnm** [comment]
Followed up with @rgnote @priteshbandi , they have accepted the invite.

**Comment by shizhMSFT** [comment]
@gokarnm Here's the list of my team who are working on notation.
- @binbin-li
- @patrickzheng200
- @Wwwsylvia
- @chloeyin
- @JeyJeyGao

**Comment by gokarnm** [comment]
@dtzar @SteveLasker , we should add Shiwei's team to the code reviewers group. Good to close this issue after that.

**Comment by gokarnm** [comment]
@SteveLasker I was not able to assign the [notation-code-reviewers](https://github.com/orgs/notaryproject/teams/notation-code-reviewers) group as a reviewer in PRs, it does not appear in the selection list. Do we need update any configuration?

**Comment by SteveLasker** [comment]
Invites sent

**Comment by SteveLasker** [comment]
Closing as the invites are sent. Please re-activate if I've missed something

**Comment by gokarnm** [comment]
@SteveLasker @dtzar I'm not able to assign [notation-code-reviewers](https://github.com/orgs/notaryproject/teams/notation-code-reviewers) as a reviewer of notation PRs. Are we missing something?

**Comment by dtzar** [comment]
Perhaps the group hasn't been assigned the "read" role yet @SteveLasker ?
https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization

**Comment by dtzar** [comment]
FYI @iamsamirzon @gokarnm @rgnote.  I resolved this with Steve yesterday.  You can now assign the notation-code-reviewers group to any of the notation repos.
