### ISSUE TITLE
Release a new version of Notary V2 specification

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/specifications#183]
It's time to release a new version of the Notary v2 spec

- [x] Decide on main commit for this release   - **_Using the latest mainline of "notaryproject" for  RC-1_**
- [x] Decide on a tag name for this release  - v1.0.0-rc.1
- [] Cut branch named with the tag name based on agreed upon main commit -  **_No need for a branch at this time_**
- [x] Cut a tag v1.0.0-rc.1

@gokarnm @dtzar @SteveLasker @FeynmanZhou @shizhMSFT @yizha1

**Comment by yizha1** [comment]
@iamsamirzon  I think this is done right?

**Comment by iamsamirzon** [comment]
yes.
