### ISSUE TITLE
Relax the certificate chain requirement for wider use case coverage

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/specifications#192]
To support additional use cases as outlined below, the certificate chain requirement imposed by the merge of https://github.com/notaryproject/notaryproject/pull/162 should be relaxed to allow for a certificate chains of any length Vs the current limit of 2.

**Desired outcome**
The notary signature-specification is updated to support the following use cases
1. Self Signed certificates

**Comment by yizha1** [comment]
@iamsamirzon  Since #162 was  done by @priteshbandi and @gokarnm, I would suggest Milind to update the spec and Pritesh to implement the fix based on the spec.

**Comment by priteshbandi** [comment]
Merged https://github.com/notaryproject/notaryproject/pull/193 and https://github.com/notaryproject/notation-core-go/pull/72

**Comment by yizha1** [comment]
> Merged #193 and [notaryproject/notation-core-go#72](https://github.com/notaryproject/notation-core-go/pull/72)

I think the 2nd PR should be https://github.com/notaryproject/notation-core-go/pull/77
