### ISSUE TITLE
COSE signingTime/authenticSigningTime/expiry type

### ISSUE THREAD

**Issue by patrickzheng200** [notaryproject/specifications#198]
Currently in our spec, we require [signingTime/authenticSigningTime/expiry](https://github.com/notaryproject/notaryproject/blob/cose-envelope/signature-envelope-cose.md#protected-header) to be of type uint. 
This caused a verification failure where the signature envelope's signingTime is of type `Tag1: datetime`, this is defined in [CBOR RFC 3.4.2](https://datatracker.ietf.org/doc/html/rfc8949#section-3.4.2). 

Created this issue to open a discussion on which way we are going:
1. Spec stays as of the current version. Signatures generated by external users are required to convert signingTime to type uint.
2. We change our spec and take `Tag1: datetime` as the type, since it's the one defined in the rfc.

**Comment by yizha1** [comment]
Notation need to align with rfc compliant signingTime, which will make notation broadly accepted.

**Comment by yizha1** [comment]
PR for updating the spec: https://github.com/notaryproject/notaryproject/pull/199

**Comment by yizha1** [comment]
Closed as spec was updated
