### ISSUE TITLE
Update Notary v2 specs to explicitly define support for both OCI 1.0 and OCI 1.1 based registries

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/specifications#214]
Based on the agreement in NV2 community call on 12/5/2022, we agreed to create a new issue to update the specifications for managing signatures in both OCI 1.0 and OCI 1.1 based registries.  

This issue will be resolved, when the specs are updated to define the behavior when pushing and verifying signatures into/from an OCI 1.0 based registry. The support for OCI 1.1 based ( reference API) is expected as is.

cc: @toddysm , @sajayantony , @vaninrao10

**Comment by sudo-bmitch** [comment]
See #112

**Comment by iamsamirzon** [comment]
Thanks @sudo-bmitch . The two issues #112 (OCI 1.0 support) and this one #214 (both OCI 1.0 and OCI 1.1 spec) are almost the same. We will tackle them both together.

**Comment by priteshbandi** [comment]
We have added support for storing signatures using both image manifest and artifact manifest 
Ref: https://github.com/notaryproject/notation/blob/main/specs/commandline/sign.md#use-oci-image-manifest-to-store-signatures
