### ISSUE TITLE
Update the branch policies for the repository

### ISSUE THREAD

**Issue by toddysm** [notaryproject/specifications#226]
After reviewing the branch policies for the repository, it seems that the `main` and release branches can benefit with more strict push and PR review policies. I would like to propose updating those as follows:

Note: @SteveLasker added checkboxes to indicate the current state

- Follow naming convention `release/<release-number>` for release branches. Example `release/rc.1`
- Use the following rules for `main` and `release/*` branches:
    - [x] Require PR before merging
    - [x] Require 3 approvals
    - [x] Dismiss stale PR approvals when new commits are pushed
    - [x] Require review from Code Owners
    - [x] Require status checks to pass before merging
    - [x] Require conversation resolution before merging
    - [x] Require signed commits
    - [x] Do not allow bypass the above settings

Please add your comments and proposals for additional changes to this issue.

**Comment by yizha1** [comment]
LGTM but IANAM

**Comment by iamsamirzon** [comment]
LGTM but IANAM

**Comment by SteveLasker** [comment]
Updated with checkboxes to indicate the current state as several of the rules were already in place.

**Comment by vaninrao10** [comment]
LGTM but IANAM

**Comment by iamsamirzon** [comment]
LGTM but IANAM

**Comment by priteshbandi** [comment]
LGTM but IANAM

**Comment by yizha1** [comment]
Closed as all polices enforced
