### ISSUE TITLE
website recent updates : notation vs "notary v2"

### ISSUE THREAD

**Issue by dims** [notaryproject/specifications#245]
https://notaryproject.dev/  website has 6 references to "Notary v2". As i understand it, the subproject name is "Notation" and not "Notary v2". 

Can you please update as needed to ensure a distinct brand for "Notation" as a sub project?

**Comment by lachie83** [comment]
Thanks @dims. I will make sure this is brought to the attention of the Notary community and that it is actioned.

**Comment by toddysm** [comment]
This item is added to the agenda for Notary community on March 6th. Agenda is available at https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw

**Comment by toddysm** [comment]
@dims The updates are in the following PR: https://github.com/notaryproject/notaryproject.dev/pull/150

**Comment by toddysm** [comment]
We are also updating references in code: https://github.com/notaryproject/roadmap/issues/89

**Comment by dims** [comment]
thanks @toddysm - feel free to close this issue as you are tracking elsewhere

**Comment by zr-msft** [comment]
https://github.com/notaryproject/notaryproject.dev/pull/150 has been merged. @toddysm  please consider closing the issue

**Comment by toddysm** [comment]
Closing the issue as per the above comment.
