### ISSUE TITLE
Error in Notation Login

### ISSUE THREAD

**Issue by julioarruda** [notaryproject/specifications#251]
I'm following this tutorial from Microsoft, step by step: https://learn.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-sign-build-push 

But when I'm trying to run the login command, I'm receiving this error

```
Error: could not get the credentials store: failed to load config file, error: credentials store config was not set up
```

Someone have any idea about this?

My environemnt:
OS: ubuntu 20.04 LTS

Notation Version
```
Notation: Notary v2, A tool to sign, store, and verify artifacts.

Version:     1.0.0-rc.3
Go version:  go1.20.1
Git commit:  233c0ea71edfb68b951eb54a739a101e2a05cd26
```

Az CLI Version
```
{
  "azure-cli": "2.47.0",
  "azure-cli-core": "2.47.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
```

**Comment by FeynmanZhou** [comment]
Hi @julioarruda ,

As mentioned in [Authenticate with OCI-compliant registries | (notaryproject.dev)](https://notaryproject.dev/docs/how-to/registry-authentication/), Notation currently relies on [Docker Credential Store](https://github.com/notaryproject/notation/blob/main/specs/registry-auth.md#credential-store). You need to configure Docker Credential Store in your Ubuntu machine. This dependency will be removed in Notation v1.0.0. 

Another alternative is to skip this `notation login` authentication. You can try `notation sign` with `-u` and `-p` flag to sign images directly. Adding these flags will bypass the [Docker Credential Store](https://github.com/notaryproject/notation/blob/main/specs/registry-auth.md#credential-store) configuration. 

We will update this Azure doc soon.

**Comment by julioarruda** [comment]
Hi @FeynmanZhou thanks for this.. It`s works now..
