### ISSUE TITLE
Update signing capability to sign GitHub Releases

### ISSUE THREAD

**Issue by Miranlfk** [notaryproject/specifications#258]
**Current Behavior -** 
Release binaries/artifacts must be pushed to an OCI compatible registry beforehand and thereafter notation can sign it.

**Proposed Improvement -**
Investigate in enhancing Notation signing capability to sign releases/binaries/artifacts published on GitHub Releases. In general release artifacts/binaries would be published in GitHub Releases, therefore supporting this capability can promote adoption better.

**Comment by toddysm** [comment]
I believe this is similar to https://github.com/notaryproject/notation/issues/741
