### ISSUE TITLE
Document how the latest implementation of Notation/Notary and TUF relate

### ISSUE THREAD

**Issue by Miranlfk** [notaryproject/specifications#259]
Documenting the current implementation of Notary and how associated with TUF would be very informative. User's may discover `Notary v1` and thereafter `Notation/Notary v2` and discussing their association with TUF and how the 2 implementations differ would provide more insight. This can be followed up with details of the inclusion of TUF in Notation as discussed in the community call [(1st June 2023)](https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw#Jun-1-2023).

**Comment by yizha1** [comment]
@Miranlfk could you verify whether this issue was solved, since we have [updated overview](https://github.com/notaryproject/.github/blob/main/README.md) and [FAQ for terminology](https://notaryproject.dev/docs/faq/#notary-project-terms) to clarify the overall Notary Project, and Terms.
