### ISSUE TITLE
Vote for the release of specifications v1.0.0

### ISSUE THREAD

**Issue by yizha1** [notaryproject/specifications#273]
Vote for the release of specifications `v1.0.0`. We need `6` approvals from the current `9` maintainers to vote for tagging [a3d1158](https://github.com/notaryproject/specifications/commit/a3d1158d5ea6274bce89ce2addef0161a142c60b) as `v1.0.0`.  As a maintainer and the one proposing this vote, my vote is +1.

Here is the link to [change log](https://github.com/notaryproject/specifications/compare/v1.0.0-rc.2...a3d1158d5ea6274bce89ce2addef0161a142c60b) .

- [ ] Justin Cormack <justin.cormack@docker.com> (@justincormack)
- [ ] Niaz Khan <niazfk@amazon.com> (@niazfk)
- [x] Steve Lasker <StevenLasker@hotmail.com> (@stevelasker)
- [x] Milind Gokarn <gokarnm@amazon.com> (@gokarnm)
- [x] Pritesh Bandi <priteshbandi@gmail.com> (@priteshbandi)
- [x] Shiwei Zhang <shizh@microsoft.com> (@shizhMSFT)
- [x] Toddy Mladenov <toddysm@gmail.com> (@toddysm)
- [ ] Vani Rao <vaninrao@amazon.com> (@vaninrao10)
- [x] Yi Zha <yizha1@microsoft.com> (@yizha1)

**Comment by shizhMSFT** [comment]
LGTM

**Comment by toddysm** [comment]
LGTM

**Comment by SteveLasker** [comment]
LGTM

**Comment by priteshbandi** [comment]
LGTM

**Comment by gokarnm** [comment]
LGTM

**Comment by yizha1** [comment]
Thanks for voting. We now reached two-thirds supermajority to release specification v1.0.0

**Comment by yizha1** [comment]
Close this issue as [Notary Project specifications v1.0.0](https://github.com/notaryproject/specifications/releases/tag/v1.0.0) has been released.
