### ISSUE TITLE
Spec updates for Arbitrary Blob Signing

### ISSUE THREAD

**Issue by rgnote** [notaryproject/specifications#281]
Proposal - https://hackmd.io/ewbJr2ZnT4a8U1ObDVXcSw?view

**Comment by ghost** [comment]
Thanks @rgnote. 
@yizha1 @FeynmanZhou As discussed, this is an issue to keep record that we need to add new specs for `Arbitrary Blob Signing` in this repo.

**Comment by yizha1** [comment]
Closed as completed by PR https://github.com/notaryproject/specifications/pull/283
