### ISSUE TITLE
Propose a new release for Specifications repo

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/specifications#294]
After [Notary Project Specifications v1.0.0](https://github.com/notaryproject/specifications/releases/tag/v1.0.0) released in Aug, there are three changes as follows:

- #292 (under PR review)
- #285 
- #291 

I propose a new release v1.1.0 for Notary Project Specifications because #292 introduces incremental changes to plugin spec. The implementation of notation CLI v1.1.0 and notation-go v1.1.0 are also based on the new Spec (plugin spec). 

Another choice is to cut a patch release v1.0.1, but in general a patch release happens when only wording issue or bug fixes exit. A patch seems not match the changes listed above

@notaryproject/notaryproject-notaryproject-maintainers please help to share your opinion on this issue. Thanks

**Comment by yizha1** [comment]
+1 for `v1.1.0` release

**Comment by yizha1** [comment]
Closed per discussion in community meeting on Mar 4, 2024.
