### ISSUE TITLE
Make it Scoopable

### ISSUE THREAD

**Issue by zachbugay** [notaryproject/specifications#297]
https://scoop.sh/#/

Scoop is a command line installer for windows, similar to Homebrew for mac.

I would like to see this added to scoop.

**Comment by yizha1** [comment]
@zachbugay Thank you for creating this issue. Would you mind confirming this is the right repo (Notary Project specifications), maybe you want to ask this for Notation CLI, the repo of which is https://github.com/notaryproject/notation.

**Comment by FeynmanZhou** [comment]
@zachbugay  Thanks. It sounds like a good proposal to me. This would be a good first issue. Are you interested in submitting Notation CLI to Scoopable?

**Comment by zachbugay** [comment]
I apologize. I was hoping to add the Notation CLI to scoop. This can be closed.
