### ISSUE TITLE
Trusted Identity configuration

### ISSUE THREAD

**Issue by ghost** [notaryproject/specifications#300]
During the design of timestamping trust policy support, we found a potential issue regarding the `trustedIdentity` field of trust policy. Currently, it's an array of [identities](https://github.com/notaryproject/specifications/blob/main/specs/trust-store-trust-policy.md#trusted-identities-constraints). However, it does not specify the trust source of each trusted identity. For example, a verifier maybe trusts an identity only when they represent a `tsa` for timestamping instead of `ca` for code signing. The current `trustedIdentity` configuration does not provide this option.

Given the above concern, I propose to refactor the trust policy and upgrade the version to `2.0`. An upgraded OCI trust policy could look like this:
```
{
    "version": "2.0",
    "trustPolicies": [
         {
            "name": <policy_name>,
            "registryScopes": [ "<registry>/<repo>"],
            "signatureVerification": {
                "level" : "strict"
            },
            "trustStores": {
                "ca": [<named stores>],
                "tsa": [<named stores>]
            },
            "trustedIdentities": {
                "ca": ["*"],
                "tsa": ["x509.subject: C=..., ..."],
            }
        }
    ]
}
```

**Comment by Two-Hearts** [comment]
@shizhMSFT @yizha1 @FeynmanZhou @JeyJeyGao

**Comment by ghost** [comment]
Based on 5/6/2024 community meeting discussion, closing this issue.
