### ISSUE TITLE
Follow-up on handling TSA SHA1 algorithm

### ISSUE THREAD

**Issue by yizha1** [notaryproject/specifications#302]
>http://timestamp.digicert.com and http://timestamp.apple.com/ts01 are returning certs with signature algorithm SHA1.
What does that mean? Certs are signed using SHA1 ?

_Originally posted by @priteshbandi in https://github.com/notaryproject/specifications/pull/290#discussion_r1637027826_

**Comment by ghost** [comment]
Restating the answer to the above questions from PR review:
Yes, here's the detail error for digicert TSA:
Error: timestamp: root certificate with subject "CN=DigiCert Assured ID Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US" is invalid or not self-signed. Certificate chain must end with a valid self-signed root certificate. Error: x509: cannot verify signature: insecure algorithm SHA1-RSA

**Comment by priteshbandi** [comment]
There is ongoing ballot in CAB forum which adds following line. This is not directly related to the issue but TSAs will nolonger support SHA 1 signing/time-stamping.
`
The Timestamp Authority SHALL reject timestamp requests containing a `MessageImprint` calculated using the SHA-1 digest algorithm.` 

---
Ballot text:

This ballot updates the “Baseline Requirements for the Issuance and Management of Publicly‐Trusted Code Signing Certificates” ("Code Signing Baseline Requirements") based on version 3.7. MODIFY the Code Signing Baseline Requirements as specified in the following redline: [https://github.com/cabforum/code-signing/compare/d431d9104094f2b89f35ed4bf1d64b9a844e762b...12130ff7c2b41d795d47925c084780ea0f7328cd](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcabforum%2Fcode-signing%2Fcompare%2Fd431d9104094f2b89f35ed4bf1d64b9a844e762b...12130ff7c2b41d795d47925c084780ea0f7328cd&data=05%7C02%7Cmartijn.katerbarg%40sectigo.com%7C1793f327db4a41d5bd0608dc8bc62ada%7C0e9c48946caa465d96604b6968b49fb7%7C0%7C0%7C638538930466512096%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=1nB1QsZHCVTKQ7UkE4Q0fLnDcl30%2B1pzuAgbvccxkgY%3D&reserved=0)

**Comment by yizha1** [comment]
Per discussion at community meeting https://hackmd.io/_vrqBGAOSUC_VWvFzWruZw?view#Notes, SHA1 will not be supported, and we can discuss specific requirements in the future if there are any asks from users. So, close this issue.
