### ISSUE TITLE
Discussion: Timestamp cert chain validation

### ISSUE THREAD

**Issue by ghost** [notaryproject/specifications#304]
While validating the tsa cert chain after signing, we must ask the signer to provide their trusted TSA root cert. This is because most of the TSA servers are using `http` instead of `https`, building cert chain using only the certs inside the timestamp countersignature may lead to a Man-In-The-Middle (MITM) attack. The tsa signing cert must be chained up to the user provided trust anchor instead.
(Besides, we found some TSAs that are not including their root certificate in the TSA response. For example:
http://timestamp.digicert.com, http://timestamp.acs.microsoft.com/)

Given above, the following are needed:
`Sign`:
Implementations of Notary Project must provide an input parameter for the signer to pass in their trusted TSA root cert. Any received timestamp countersignature must successfully build a certification chain tracing to this root cert. If no such chain can be built, fail the signing process. If the user does not provide their tsa trust anchor, fail the signing process.

`Verify`:
Since a verifier MUST configure trust policy and trust store before timestamp verification. Use the user's trust store to build the chain. The workflow is then: `get the applicable trust policy` -> `fetch user trusted tsa root certificates from user trust store as the root cert pool` -> `during timestamp verification, check if a chain can be built to one of the trusted tsa root certs`. This workflow aligns with the validation process after `Signing`.

**Comment by ghost** [comment]
Based on discussion in the 6/24/24 community meeting, we will use the above sign/verify workflows and have future iterations if new use cases/requirements occur.

**Comment by ghost** [comment]
An update to TSA "http://timestamp.digicert.com", as it's a popular free TSA:
Before we made the change stated above, `digicert TSA` won't work because it only contains a root cert with `SHA1-RSA` in its timestamp countersignature. Since we were trying to build the chain with certs only inside the timestamp, the result chain won't pass Notation's validation.

Now, if we require the signer providing their trusted tsa root cert, `digicert TSA` starts to work again. This is because its root cert can be download from https://knowledge.digicert.com/general-information/rfc3161-compliant-time-stamp-authority-server. The root cert `DigiCertTSARootSHA384.cer` is `SHA384-RSA`, which can pass Notation's validation. And since the certs inside timestamp signature can be chained up to `DigiCertTSARootSHA384.cer` as well, Notation signers are able to require timestamp from `digicert TSA` again.

**Comment by priteshbandi** [comment]
IMO we can start with not supporting SHA1 but later if get significant request in future we can add the support.
