### ISSUE TITLE
vote: tag v1.1.0-rc.1

### ISSUE THREAD

**Issue by yizha1** [notaryproject/specifications#314]
## Release

Tag https://github.com/notaryproject/specifications/commit/25e9940f9ac83b2647885b47e9e952be92e8c64f as `v1.1.0-rc.1`. 

## Vote

We need `4` approvals from the current `7` maintainers to release `specifications` `v1.1.0-rc.1`.

- [ ] Niaz Khan <niazfk@amazon.com> (@niazfk)
- [ ] Milind Gokarn <gokarnm@amazon.com> (@gokarnm)
- [ ] Pritesh Bandi <priteshbandi@gmail.com> (@priteshbandi)
- [x] Shiwei Zhang <shizh@microsoft.com> (@shizhMSFT)
- [x] Toddy Mladenov <toddysm@gmail.com> (@toddysm)
- [x] Vani Rao <vaninrao@amazon.com> (@vaninrao10)
- [x] Yi Zha <yizha1@microsoft.com> (@yizha1)

## Changes

Here is the link to the full change log: https://github.com/notaryproject/specifications/compare/v1.0.0...25e9940

## Action Requested

Please respond LGTM or REJECT (with reasoning).

**Comment by yizha1** [comment]
LGTM

**Comment by vaninrao10** [comment]
LGTM

**Comment by shizhMSFT** [comment]
LGTM

**Comment by toddysm** [comment]
LGTM

**Comment by yizha1** [comment]
Thanks everyone. Closed this issue as released https://github.com/notaryproject/specifications/releases/tag/v1.1.0-rc.1
