### ISSUE TITLE
Meta: Project Governance and Structure?

### ISSUE THREAD

**Issue by dlorenc** [notaryproject/specifications#55]
I was a little confused as to the basic details and governance of this project. I did some looking but wasn't able to find anything definitive:

- Is this part of the OCI or the CNCF?
  - I think the answer is the CNCF based on the slack and zoom and stuff.
- Is this part of the same CNCF "project" as Notary v1?
  - The Github org name (notaryproject) implies it is the same project, but that repo is part of [TUF](https://github.com/theupdateframework/notary).
  - Who will own the proposed specifications here? The OCI or the CNCF?
- Basic governance and decision making?
  - The notary project has some stuff [here](https://github.com/theupdateframework/notary/blob/master/MAINTAINERS_RULES.md), but the TUF project has different [stuff](https://github.com/theupdateframework/tuf/blob/develop/docs/GOVERNANCE.md)
    - I think Notary is separate from TUF - they just share a GitHub org. 
  - Does this org use the Notary ones? If so - who are the MAINTAINERS?
 
Apologies if I've missed this somewhere!

**Comment by SteveLasker** [comment]
There are a number of parts to this end-to-end story for the integrity of content within a registry. We outlined the [Top Areas of Focus](https://github.com/notaryproject/notaryproject#top-areas-of-focus) in the project root and status updates.

For which efforts go into which project:

- The Notary v2 signature will be part of the CNCF Notary Project
- Registry Persistence, Discovery, and Retrieval will be part of [OCI Artifacts](https://github.com/opencontainers/artifacts). OCI Artifacts was created as it was believed distribution should stay focused on the underlying primitives of content distribution. We would like to see Artifacts and Distribution merged as the separation makes it difficult for consumers to understand. Until that time, we're pursuing extensions to distribution to enable Notary v2 requirements.
- Key Management is still being clarified and would be part of Notary v2. I'd say it's too early to state whether additional services will be required. This is part of the perf, scale, usability, and how they equate back to the core requirements. We're being very careful to not start with project __ is the answer, rather what designs meet the requirements. If existing projects can meet the requirements, or if changes to existing projects meet the requirements, even better. 

As for standards and specifications:
I believe we're shooting for both a spec for consumers to implement in the patterns and tools they need. and standards to enable people to easily get started. 

To that end, the `nv2` client will provide a set of binaries consumers can use, while /notary will contain the libraries people can consume. This does currently assume libraries around go, but that should NOT be a constraint, rather a starting point. As the specs evolve, new language libraries would considered.

**Comment by lachie83** [comment]
@justincormack is working on this via https://github.com/theupdateframework/notary/pull/1606

**Comment by dtzar** [comment]
Pretty sure we've covered the original ask of this issue, so closing out.  If you feel you still need more information @dlorenc let us know.
