### ISSUE TITLE
Key Management - Rescinding Certificates

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/specifications#72]
Created to get feedback on https://hackmd.io/2rc07WwHTdmPjpgoMbvYfA?view  from the NotaryV2 working group

**Comment by sudo-bmitch** [comment]
This should probably be a PR on https://github.com/notaryproject/notaryproject/blob/main/key-revocation.md

**Comment by shizhMSFT** [comment]
Artifact-level signature rescidning can go to #88.

**Comment by dtzar** [comment]
On the community call today, there are several places where this is in the documents which need consolidation.  Also the https://github.com/notaryproject/notaryproject/blob/main/key-revocation.md seems like it should be more of certificate revocation, not "keys".  For RC-1 we need to just finalize the spec in an agreed upon md document.  The [hack md doc](https://hackmd.io/2rc07WwHTdmPjpgoMbvYfA?view) presents all the different options and we've narrowed down the approach we want to take, but it needs to be documented.  

Proposal on the table would be to [consolidate to this location](https://github.com/notaryproject/notaryproject/blob/main/trust-store-trust-policy-specification.md#certificate-revocation-evaluation) for the final spec.

**Comment by vaninrao10** [comment]
Current Draft version is what will be considered in RC-1, this has been aligned in the community call as of 11/21/2022

**Comment by yizha1** [comment]
As discussed in the community meeting on Nov 4, 2024, Notary Project supports certificate revocation. Close this issue as completed
