### ISSUE TITLE
Request for formal governance documentation and additional maintainers

### ISSUE THREAD

**Issue by mnm678** [notaryproject/specifications#77]
As discussed in the 6/25 weekly meeting, there are a lot of unmerged prs sitting in this repository. To address this, it would be nice to have a more formal process for getting prs merged, such as approval from multiple maintainers. To this end, we need more than 2 people able to approve and merge prs.

**Comment by mnm678** [comment]
I would also like to put myself forward as a potential maintainer.

**Comment by dlorenc** [comment]
I second @mnm678's nomination!

I'd also like to nominate @sudo-bmitch and myself (@dlorenc).

**Comment by trishankatdatadog** [comment]
I second @mnm678 @dlorenc and @sudo-bmitch.

I'd like to nominate myself, too, as a representative for Datadog who has a clear interest in this moving forward.

**Comment by dlorenc** [comment]
Ref https://github.com/notaryproject/notaryproject/issues/55

**Comment by gokarnm** [comment]
I would like to nominate myself as a potential maintainer as a representative for AWS (@gokarnm). AWS has been involved in contributions to this project and is interested in moving this project forward.

**Comment by trishankatdatadog** [comment]
> To this end, we need more than 2 people able to approve and merge prs.

As with Uptane, which has stakeholders from multiple orgs, I recommend that reviews gather approval from not just more than 2 maintainers, but maintainers from separate orgs.

**Comment by lachie83** [comment]
I will work on getting a GOVERNANCE.MD together taken from other projects in the CNCF.

**Comment by sudo-bmitch** [comment]
For completeness, I'm happy to volunteer myself as a maintainer. (GitHub ID @sudo-bmitch)

**Comment by anvega** [comment]
In addition to the great list of folks nominated thus far, I'd like to also submit @nishakm and @joshuagl for consideration. Should both of them be willing, I think both possess the ability to help maintain the project in an official capacity.

**Comment by anvega** [comment]
It would probably be beneficial to discuss the total number of maintainer seats.  A couple of considerations: This number should account for  healthy distribution of responsibility/load given the current volume of project activity, and second, an odd number is highly desirable for dispute resolution.

A project that has gone through a lot of deliberation and refinement of governance processes is the spiffe project. There is plenty that can be borrowed and extrapoloted from the lessons:

**Comment by anvega** [comment]
A starting point might be to arrive at a proposed number of maintainer seats. The number chosen should account for what represents a healthy distribution of responsibility/load given the current and projected volume of project activity.  Typically, an odd number is highly desirable for dispute resolution.

A project that has gone through plenty of deliberation and refinement of its governance procedures is the spiffe project. Here are couple links that might serve as a reference to extrapolate from:

- [Governance](https://github.com/spiffe/spiffe/blob/main/GOVERNANCE.md)
- [Maintainers](https://github.com/spiffe/spire/blob/main/MAINTAINERS.md)

**Comment by lachie83** [comment]
Please review #78. The idea was to start with a lightweight governance structure to establish who the maintainers are and the process to become a maintainer.  Once we get initial quorum of maintainers they can then choose to further build out the governance structure.

**Comment by lachie83** [comment]
> A starting point might be to arrive at a proposed number of maintainer seats. The number chosen should account for what represents a healthy distribution of responsibility/load given the current and projected volume of project activity. Typically, an odd number is highly desirable for dispute resolution.
> 
> A project that has gone through plenty of deliberation and refinement of its governance procedures is the spiffe project. Here are couple links that might serve as a reference to extrapolate from:
> 
> * [Governance](https://github.com/spiffe/spiffe/blob/main/GOVERNANCE.md)
> * [Maintainers](https://github.com/spiffe/spire/blob/main/MAINTAINERS.md)

These are a great set of docs. Thanks for sharing. In addition, I've also seen this format which has come from the some of the members of SIG Contributor experience https://github.com/openservicemesh/osm/blob/main/CONTRIBUTING_LADDER.md.

**Comment by nishakm** [comment]
> In addition to the great list of folks nominated thus far, I'd like to also submit @nishakm and @joshuagl for consideration. Should both of them be willing, I think both possess the ability to help maintain the project in an official capacity.

I'm in! Happy to volunteer as a maintainer :)

**Comment by joshuagl** [comment]
> In addition to the great list of folks nominated thus far, I'd like to also submit @nishakm and @joshuagl for consideration. Should both of them be willing, I think both possess the ability to help maintain the project in an official capacity.

I appreciate the nomination, I'd be very happy to help.

**Comment by lachie83** [comment]
@justincormack is working on this here https://github.com/theupdateframework/notary/pull/1606

**Comment by dtzar** [comment]
Closing this out since we do have a [formal governance document](https://github.com/notaryproject/notary/blob/master/GOVERNANCE.md).  If you'd like to get involved in the project as a maintainer for notary v2 (notation), showing up meet twice a week on the community calls is a good start.
