### ISSUE TITLE
Key Management - Signature Expiry

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/specifications#81]
Tracking the iteration in https://hackmd.io/pT4IicsQRlGhR9szlrIUWQ, converting to a PR

**Comment by yizha1** [comment]
@SteveLasker recommend closing this issue since signature expiry is already documented in spec https://github.com/notaryproject/notaryproject/blob/main/trust-store-trust-policy-specification.md

**Comment by dtzar** [comment]
Agreed.  @SteveLasker if you think we still need this or something different with expiry in the spec, I suggest opening a more detailed issue to address.
