### ISSUE TITLE
Key Management - Trust Policy Management and Trust Store Updates

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/specifications#83]
Tracking https://hackmd.io/V55tsqsOQNmVYBFCr_DS5g for PR creation

**Comment by yizha1** [comment]
@gokarnm @priteshbandi @vaninrao10 Could you please check whether anything else left from rc.1 besides the CLI command to manage trust policy.

**Comment by yizha1** [comment]
As discussed in the community meeting on Nov 4, 2024, this issue will be closed as completed.
