### ISSUE TITLE
Key Management - Signing Key Expiry

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/specifications#84]
Tracking https://hackmd.io/n82ZTBv3TK2Y4rujlnW3ng for conversion to a PR

**Comment by shizhMSFT** [comment]
This should probably be a PR on https://github.com/notaryproject/notaryproject/blob/main/key-revocation.md

**Comment by iamsamirzon** [comment]
Certificate expiry is considered as part of Signature validation in the specs. We can close this item. https://github.com/notaryproject/notaryproject/blob/main/trust-store-trust-policy-specification.md#signature-verification
