### ISSUE TITLE
Key Management - Rescinding Signature Validity

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/specifications#85]
Tracking https://hackmd.io/TnX8l31CQnGPRujZ_gLGJA, which may be a dupe of #72

**Comment by iamsamirzon** [comment]
Closing this lieu of open roadmap items, https://github.com/notaryproject/roadmap/issues/11 and https://github.com/notaryproject/roadmap/issues/12, which are in plan for RC-2
