### ISSUE TITLE
Finalize the signature/envelop spec

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/specifications#99]
Tracking the finalization of #86 as an update to https://github.com/notaryproject/notation/blob/prototype-2/docs/signature/README.md

**Comment by sudo-bmitch** [comment]
I believe this is also associated with #93

**Comment by iamsamirzon** [comment]
@dtzar , Closing as the signature spec is merged and available here. https://github.com/notaryproject/notaryproject/blob/main/signature-specification.md
